# Generated by Django 5.0.4 on 2024-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
